<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.J7dFThm' shared service.

return $this->privates['.service_locator.J7dFThm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
]);
